### ISSUE TITLE
Support for rendering multiple tile sets - v0.3.0

### ISSUE THREAD

**Issue by panicdragon** [webcyou-org/flame_isometric#1]
### ToDo List

- [x]  Allow specifying the appropriate sheet and index from the matrix. （x, y）
- [x]  Provides API for 1D arrays
- [x]  Tile map attribute acquisition
